services:
  db:
    image: postgres:16
    restart: always
    shm_size: 256mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../source:/source:ro
      - ./init:/docker-entrypoint-initdb.d:ro
    networks:
      - ktdl-network

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - "${ADMINER_PORT:-8082}:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    networks:
      - ktdl-network

volumes:
  postgres_data:

networks:
  ktdl-network:
    external: true
