services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - ktdl-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    networks:
      - ktdl-network

networks:
  ktdl-network:
    external: true
